### PR TITLE
AIR 20 and MacOS 64 bit support added

### PR DESCRIPTION
**Pull request by kernelex**
Hi! Łukasz!
Once I asked you about Mac 64bit support. 
So I've spend a little time (actually not little but anyway... ) and here what I've done. 
Please look at it and may be this could be helpful for others. 
There is also resulted 64 ANE and xcode project.
Also I added build64.command for it.

cheers,
Alex V.

### CODE REVIEW

**Comment by b005t3r** [comment]
Wow, you had to change almost everything :) I'll give it a go next week, I promise, and let you know, OK?

**Comment by kernelex** [comment]
Actually not so much changed )
And may be nothing on code..
There are 2 additional projects
- Flex project for 64 swc.
- and xcode project for 64.
  They are almost duplicates of yours
  Just with new settings
  And separate build command.

For the 32 bit projects  you can skip my changes

**Comment by b005t3r** [comment]
Still haven't tested it, because the thing I planned for this week is taking more time than I though, but as soon as it's finished I'll give it a go.

**Comment by kernelex** [comment]
No problem. Take your time )

**Comment by b005t3r** [comment]
Still on my TODO list, things I'm busy with are taking much longer than expected. I'm still using AIR17 and testing this would require updating a bunch of projects to the most recent version, so have to finish my stuff first. Sorry for the delay once again.

**Comment by b005t3r** [comment]
Finally managed to find some time and merged your changes! Thanks a lot, I tested it with my current project and everything seems to work beautifully 👍

**Comment by sushihangover** [comment]
Perfect timing, just needed this again, but for 64bit!!!!!  Thanks Everyone (@kernelex Nice work)

**Pull request merged**
